### ISSUE TITLE
cannot find -lgflags_static

### ISSUE THREAD

**Issue by 1gen100** [jhu-lcsr/handeye_calib_camodocal#24]
Hey, I am trying to get the program running but I can't seem to get it working because of a recurring error that I can't debug, hope you can help me.

~/catkin_ws$ catkin_make

Base path: /home/student/catkin_ws
Source space: /home/student/catkin_ws/src
Build space: /home/student/catkin_ws/build
Devel space: /home/student/catkin_ws/devel
Install space: /home/student/catkin_ws/install
####
####
####
####
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target std_msgs_generate_messages_py
[ 13%] Built target kinect2_registration
[ 13%] Built target _beginner_tutorials_generate_messages_check_deps_Num
[ 13%] Built target _beginner_tutorials_generate_messages_check_deps_AddTwoInts
[ 16%] Linking CXX executable /home/student/catkin_ws/devel/lib/handeye_calib_camodocal/handeye_calib_camodocal
[ 26%] Built target beginner_tutorials_generate_messages_eus
[ 33%] Built target beginner_tutorials_generate_messages_cpp
[ 40%] Built target beginner_tutorials_generate_messages_lisp
[ 53%] Built target beginner_tutorials_generate_messages_py
[ 60%] Built target kinect2_calibration
[ 66%] Built target kinect2_bridge
[ 73%] Built target kinect2_bridge_nodelet
[ 80%] Built target beginner_tutorials_generate_messages_nodejs
[ 86%] Built target talker
[ 93%] Built target listener
[ 93%] Built target beginner_tutorials_generate_messages
/usr/bin/ld: cannot find -lgflags_static
collect2: error: ld returned 1 exit status
handeye_calib_camodocal/CMakeFiles/handeye_calib_camodocal.dir/build.make:215: recipe for target '/home/student/catkin_ws/devel/lib/handeye_calib_camodocal/handeye_calib_camodocal' failed
make[2]: *** [/home/student/catkin_ws/devel/lib/handeye_calib_camodocal/handeye_calib_camodocal] Error 1
CMakeFiles/Makefile2:2359: recipe for target 'handeye_calib_camodocal/CMakeFiles/handeye_calib_camodocal.dir/all' failed
make[1]: *** [handeye_calib_camodocal/CMakeFiles/handeye_calib_camodocal.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by FJarecki** [comment]
Hi, Do u solve this problem? How?
