### ISSUE TITLE
Camera pose Matrix 

### ISSUE THREAD

**Issue by alessmosca** [jhu-lcsr/handeye_calib_camodocal#3]
Hello, 
I'm trying to make a hand eye calibration, but I'm bit stacked! I would like to use the AX=XB method, that, since I understood is the one implemented using comodocal. I read from your presentation the mainly the input for the algorithm are the pose of the robot refers to its base, and the pose of the camera refers to the object ( in my case a chessboard ). Regarding the pose of the camera, I'm computing it using the extrinsic parameters, with this method I get the rotation matrix (unit is radiants )and the traslation matrix (unit is pixel, I guess ). now the problem is that I'm not really sure if this matrix, is the right one for the algorithm. 
Could you help me to remove this doubt and clarify the mind ?

**Comment by ahundt** [comment]
[problem is solved](https://github.com/jhu-lcsr/handeye_calib_camodocal/issues/2#issuecomment-306705302), enjoy!
