### ISSUE TITLE
terminate called after throwing an instance of 'std::system_error'

### ISSUE THREAD

**Issue by Sofiap91** [jhu-lcsr/handeye_calib_camodocal#39]
Hello, I getting this error every time I try to run both handeye_example.launch and handeye_file.launch.
Any Ideas on how to solve it? 

![image](https://user-images.githubusercontent.com/20958061/113040105-c9065e80-916e-11eb-94e2-7654a2669705.png)

Thanks.

**Comment by aquibrash87** [comment]
@Sofiap91 did you solve the problem? Can you please comment on the issue.

**Comment by Sofiap91** [comment]
No, sorry, we didn't.
