### ISSUE TITLE
cankin_make error 

### ISSUE THREAD

**Issue by james2254** [jhu-lcsr/handeye_calib_camodocal#5]
When I run "cankin_make", there is an error that could not find glog, but I can find libglog.so.0.0.0 in /usr/lib, I have installed the package of glog-0.3.4.
`CMake Error at handeye_calib_camodocal-master/CMakeLists.txt:30 (find_package):
  By not providing "FindGlog.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Glog", but
  CMake did not find one.

  Could not find a package configuration file provided by "Glog" with any of
  the following names:

    GlogConfig.cmake
    glog-config.cmake

  Add the installation prefix of "Glog" to CMAKE_PREFIX_PATH or set
  "Glog_DIR" to a directory containing one of the above files.  If "Glog"
  provides a separate development package or SDK, be sure it has been
  installed.
`

**Comment by sundw2014** [comment]
Ubuntu 14.04
I encountered the same problem. Building glog from source using cmake solved this problem.

**Comment by ahundt** [comment]
Yes, you need to install a more recent version of glog, either the cmake config file didn't exist when the package was made or the ubuntu package maintainers forgot to include it, which I've also seen happen on a number of occasions.

**Comment by ahundt** [comment]
feel free to comment if there is still a problem

**Comment by StanleyYake** [comment]
I was on Ubuntu 14.04 and ROS indigo.Even when I install gflags and glog from source, and still can't catkin_make successful.Looking at glog github, they build with `./autogen.sh && ./configure && make && make install` routine, catkin_make fail. so I use common `mkdir build;cd build; cmake ..;make; make install` which will install cmake config file(I recommand this way to install) and then catkin_make told the cmake version is low.After upgrade Cmake and softlink `sudo ln -s /usr/local/lib/libgflags.so /usr/lib/x86_64-linux-gnu/` and `sudo ln -s /usr/local/lib/libglog.so /usr/lib/x86_64-linux-gnu/` and all things catkin_make successfully.

**Comment by ahundt** [comment]
tray catkin build rather than catkin make

**Comment by hongtaowu67** [comment]
I use the cmake way to make the downloaded source file of glog and catkin_make successfully.
